version: "3.9"

services:

 redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

 db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${POSTGRES_NAME} -U ${POSTGRES_USER} -P ${POSTGRES_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 5

 backend:
    build:
      context: .
      dockerfile: dockerfiles/dev/django/Dockerfile
    container_name: backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - SHOW_DEBUGGER_TOOLBAR=${SHOW_DEBUGGER_TOOLBAR}
      - ALLOW_HOST=${ALLOW_HOST}
      - SHOW_SWAGGER=${SHOW_SWAGGER}
    restart: always
    depends_on:
      - db
      - redis

